# Generated by Django 5.0.6 on 2024-06-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('papeterie', 'Papeterie'), ('electronique', 'Électronique')], max_length=50)),
                ('nom', models.CharField(max_length=100)),
                ('quantite', models.IntegerField(default=0)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_tva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remise', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prix_total_ttc', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
