# Generated by Django 5.0.6 on 2024-06-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix_total_ttc',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
